export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  OPERATOR = 'OPERATOR',
}

export enum FarmRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  MEMBER = 'MEMBER',
}

export enum AreaType {
  PASTO = 'PASTO',
  TALHAO = 'TALHAO',
  GALPAO = 'GALPAO',
  OUTRO = 'OUTRO',
}

export enum ProcessCategory {
  PLANTIO = 'PLANTIO',
  COLHEITA = 'COLHEITA',
  MANEJO = 'MANEJO',
  IRRIGACAO = 'IRRIGACAO',
  OUTRO = 'OUTRO',
}

export enum AnimalSex {
  MACHO = 'MACHO',
  FEMEA = 'FEMEA',
}

export enum AnimalStatus {
  ATIVO = 'ATIVO',
  VENDIDO = 'VENDIDO',
  MORTO = 'MORTO',
  OUTRO = 'OUTRO',
}

export enum GeneticMaterialType {
  SEMEN = 'SEMEN',
  EMBRIAO = 'EMBRIAO',
}

export enum StockMovementType {
  ENTRADA = 'ENTRADA',
  SAIDA = 'SAIDA',
  AJUSTE = 'AJUSTE',
}

export enum AnimalSaleType {
  ASPIRACAO = 'ASPIRACAO',
  VENDA_ANIMAL = 'VENDA_ANIMAL',
  VENDA_SEMEN = 'VENDA_SEMEN',
  VENDA_EMBRIAO = 'VENDA_EMBRIAO',
  SERVICO_ACASALAMENTO = 'SERVICO_ACASALAMENTO',
  OUTRO = 'OUTRO',
}

export enum FarmEventType {
  LEILAO = 'LEILAO',
  VENDA_EXTERNA = 'VENDA_EXTERNA',
  VENDA_FAZENDA = 'VENDA_FAZENDA',
  OUTRO = 'OUTRO',
}

export enum FarmEventStatus {
  PLANEJADO = 'PLANEJADO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO',
}

export enum SaleAssetScope {
  PRODUTO_GENETICO = 'PRODUTO_GENETICO',
  SERVICO_REPRODUTIVO = 'SERVICO_REPRODUTIVO',
  COTA_ANIMAL = 'COTA_ANIMAL',
  ANIMAL_INTEIRO = 'ANIMAL_INTEIRO',
}

export enum PaymentCondition {
  A_VISTA = 'A_VISTA',
  PARCELADO = 'PARCELADO',
}

export enum AnimalExpenseType {
  VETERINARIO = 'VETERINARIO',
  ALIMENTACAO = 'ALIMENTACAO',
  MANEJO = 'MANEJO',
  REPRODUCAO = 'REPRODUCAO',
  OUTRO = 'OUTRO',
}

export enum FinanceSection {
  COTIDIANO = 'COTIDIANO',
  FIXOS_RECORRENTES = 'FIXOS_RECORRENTES',
  OPERACIONAL = 'OPERACIONAL',
  PESSOAL_FOLHA = 'PESSOAL_FOLHA',
  PECUARIA_EVENTOS = 'PECUARIA_EVENTOS',
  INVESTIMENTOS = 'INVESTIMENTOS',
  PARCEIROS = 'PARCEIROS',
}

export enum LedgerEntryType {
  RECEITA = 'RECEITA',
  DESPESA = 'DESPESA',
}

export enum LedgerScope {
  FAZENDA = 'FAZENDA',
  EVENTO = 'EVENTO',
  ANIMAL = 'ANIMAL',
  ANIMAL_EVENTO = 'ANIMAL_EVENTO',
  AREA = 'AREA',
  FUNCIONARIO = 'FUNCIONARIO',
}

export enum LedgerCategory {
  VENDA_ANIMAL = 'VENDA_ANIMAL',
  VENDA_GENETICO = 'VENDA_GENETICO',
  OUTRA_RECEITA = 'OUTRA_RECEITA',
  APORTE_PARCEIRO = 'APORTE_PARCEIRO',
  COMPRA_INSUMO = 'COMPRA_INSUMO',
  COMBUSTIVEL = 'COMBUSTIVEL',
  MANUTENCAO = 'MANUTENCAO',
  ALIMENTACAO = 'ALIMENTACAO',
  VETERINARIO = 'VETERINARIO',
  REPRODUCAO = 'REPRODUCAO',
  DESLOCAMENTO = 'DESLOCAMENTO',
  COMISSAO_LEILAO = 'COMISSAO_LEILAO',
  HOSPEDAGEM = 'HOSPEDAGEM',
  ENERGIA = 'ENERGIA',
  AGUA = 'AGUA',
  TELEFONE_INTERNET = 'TELEFONE_INTERNET',
  ARRENDAMENTO = 'ARRENDAMENTO',
  SEGURO = 'SEGURO',
  FINANCIAMENTO = 'FINANCIAMENTO',
  IMPOSTO_TAXA = 'IMPOSTO_TAXA',
  SALARIO = 'SALARIO',
  FERIAS_13 = 'FERIAS_13',
  ENCARGOS = 'ENCARGOS',
  ADIANTAMENTO = 'ADIANTAMENTO',
  BENEFICIO = 'BENEFICIO',
  MAQUINA_EQUIPAMENTO = 'MAQUINA_EQUIPAMENTO',
  BENFEITORIA = 'BENFEITORIA',
  TERRA_MELHORIA = 'TERRA_MELHORIA',
  DISTRIBUICAO_PARCEIRO = 'DISTRIBUICAO_PARCEIRO',
  OUTRA_DESPESA = 'OUTRA_DESPESA',
}

export enum LedgerSource {
  MANUAL = 'MANUAL',
  ANIMAL_SALE = 'ANIMAL_SALE',
  ANIMAL_EXPENSE = 'ANIMAL_EXPENSE',
  RECORRENTE = 'RECORRENTE',
  FOLHA_PAGAMENTO = 'FOLHA_PAGAMENTO',
  PARCELA_VENDA = 'PARCELA_VENDA',
}

export enum InstallmentStatus {
  ABERTA = 'ABERTA',
  PAGA = 'PAGA',
  CANCELADA = 'CANCELADA',
}

export enum RecurrenceFrequency {
  MENSAL = 'MENSAL',
  BIMESTRAL = 'BIMESTRAL',
  TRIMESTRAL = 'TRIMESTRAL',
  SEMESTRAL = 'SEMESTRAL',
  ANUAL = 'ANUAL',
}

export enum PayrollRunStatus {
  RASCUNHO = 'RASCUNHO',
  FECHADO = 'FECHADO',
  PAGO = 'PAGO',
}
